### ISSUE TITLE
Uses node-gyp and Python which are not mentioned in the install

### ISSUE THREAD

**Issue by JonathanRowell** [zyrorl/chai-xsd-schema#1]
Trying to install this module to my Mocha and Chai tests on Windows gave me the following message

C:\alma\node_modules\libxmljs-mt>if not defined npm_config_node_gyp (node "C:\Users\Jonathan\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\no
de-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Jonathan\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )                                          
gyp ERR! configure error                                                                                                                                                                        
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.                                                                                               
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Jonathan\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)                                          
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Jonathan\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)                                           
gyp ERR! stack     at C:\Users\Jonathan\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29                                                                       
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)                                                                                                                                       
gyp ERR! System Windows_NT 6.1.7601                                                                                                                                                             
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Jonathan\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"                      
gyp ERR! cwd C:\alma\node_modules\libxmljs-mt                                                                                                                                                   
gyp ERR! node -v v8.9.3                                                                                                                                                                         
gyp ERR! node-gyp -v v3.6.2                                                                                                                                                                     
gyp ERR! not ok                                                                                                                                                                                 

This thing requires node-gyp which is exceedingly problematic on Windows.

The docu needs a warning that these modules are required.

**Comment by mvtm-dn** [comment]
AFAIK these dependencies is inherited from libxml-xsd.
